"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.handler = void 0;

require("source-map-support/register");

var _errorResponse = _interopRequireDefault(require("./error-response"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.4.1
var handler;
exports.handler = handler;

exports.handler = handler = async function (event, context, callback) {
  var e, request, response;

  try {
    ({
      request,
      response
    } = event.Records[0].cf);

    if (response.status === 404 && request.headers["accept"][0].value === "text/html") {
      return callback(null, (await (0, _errorResponse.default)(request)));
    }

    return callback(null, response);
  } catch (error) {
    e = error;
    console.log(e);
    return callback(null, response);
  }
};
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9pbmRleC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7OztBQUFBOztBQUNBOzs7OztBQURBLElBQUEsT0FBQTs7O0FBR0Esa0JBQUEsT0FBQSxHQUFVLGdCQUFBLEtBQUEsRUFBQSxPQUFBLEVBQUEsUUFBQSxFQUFBO0FBQ1IsTUFBQSxDQUFBLEVBQUEsT0FBQSxFQUFBLFFBQUE7O0FBQUEsTUFBQTtBQUNFLEtBQUE7QUFBQSxNQUFBLE9BQUE7QUFBQSxNQUFBO0FBQUEsUUFBc0IsS0FBSyxDQUFDLE9BQU4sQ0FBYyxDQUFkLEVBQXRCLEVBQUE7O0FBRUEsUUFBRyxRQUFRLENBQVIsTUFBQSxLQUFBLEdBQUEsSUFDQSxPQUFPLENBQUMsT0FBUixDQUFnQixRQUFoQixFQUEwQixDQUExQixFQUFBLEtBQUEsS0FESCxXQUFBLEVBQUE7QUFFRSxhQUFPLFFBQUEsQ0FBQSxJQUFBLEdBQWUsTUFBTSw0QkFGOUIsT0FFOEIsQ0FBckIsRUFBUDs7O1dBRUYsUUFBQSxDQUFBLElBQUEsRUFQRixRQU9FLEM7QUFQRixHQUFBLENBQUEsT0FBQSxLQUFBLEVBQUE7QUFTTSxJQUFBLENBQUEsR0FBQSxLQUFBO0FBQ0osSUFBQSxPQUFPLENBQVAsR0FBQSxDQUFBLENBQUE7V0FDQSxRQUFBLENBQUEsSUFBQSxFQVhGLFFBV0UsQzs7QUFaTSxDQUFWIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IFwic291cmNlLW1hcC1zdXBwb3J0L3JlZ2lzdGVyXCJcbmltcG9ydCBlcnJvclJlc3BvbnNlIGZyb20gXCIuL2Vycm9yLXJlc3BvbnNlXCJcblxuaGFuZGxlciA9IChldmVudCwgY29udGV4dCwgY2FsbGJhY2spIC0+XG4gIHRyeVxuICAgIHtyZXF1ZXN0LCByZXNwb25zZX0gPSBldmVudC5SZWNvcmRzWzBdLmNmXG5cbiAgICBpZiByZXNwb25zZS5zdGF0dXMgPT0gNDA0ICYmXG4gICAgICAgcmVxdWVzdC5oZWFkZXJzW1wiYWNjZXB0XCJdWzBdLnZhbHVlID09IFwidGV4dC9odG1sXCJcbiAgICAgIHJldHVybiBjYWxsYmFjayBudWxsLCBhd2FpdCBlcnJvclJlc3BvbnNlIHJlcXVlc3RcblxuICAgIGNhbGxiYWNrIG51bGwsIHJlc3BvbnNlXG5cbiAgY2F0Y2ggZVxuICAgIGNvbnNvbGUubG9nIGVcbiAgICBjYWxsYmFjayBudWxsLCByZXNwb25zZVxuXG5leHBvcnQge2hhbmRsZXJ9XG4iXSwic291cmNlUm9vdCI6Ii4uIn0=
//# sourceURL=/Users/david/repos/haiku9/edge-lambdas/primary/origin-response/src/index.coffee