// Generated by CoffeeScript 1.9.1
(function() {
  var Middleware, app, resolve, root;

  resolve = require("path").resolve;

  Middleware = require("./middleware");

  app = require("express")();

  root = resolve("public");

  app.use(Middleware.create(root));

  module.exports = app;

}).call(this);
